FROM python:3.9-slim

RUN apt-get update

RUN pip install --upgrade pip

COPY requirements.txt /

RUN pip install -r requirements.txt

WORKDIR /opt/app

COPY ./cassandra_consumer.py ./variables.py ./cassandra_client.py .

ENTRYPOINT ["python", "cassandra_consumer.py"]